[package]
name = "revenant-collector"
version = "0.1.0"
edition = "2024"

[lib]
name = "revenant_collector"
crate-type = ["cdylib", "staticlib"]

[dependencies]
backtrace = "0.3"
cpp_demangle = "0.5.0"
comfy-table = "7.2.0"
libc = "0.2.177"
serde = { version = "1.0.228", features = ["derive"] }